version: '3'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    image: valera-proxy:1.0
    links:
      - app
    ports:
      - "80:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PROXY=app:9000

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    image: valera-app:1.0
    environment:
      ENV: DEV
    volumes:
      - ./app:/var/www
