FROM php:7.3-fpm

RUN groupadd -r www && useradd -r -g www www

RUN apt-get update
RUN apt-get install -y libzip-dev zip

RUN docker-php-ext-configure zip --with-libzip

RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-install zip

COPY app/ /var/www
COPY app/cmd.sh /
WORKDIR /var/www/public


CMD ["/cmd.sh"]