FROM nginx:1.14

COPY proxy/default.conf /etc/nginx/conf.d/default.conf
COPY ./app/public /var/www/public
COPY proxy/entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
